On branch x86_64
PortsMaster/PortMaster-GUI pull request #91
Opened 2024-03-21 09:47 UTC by monkeyx-net

modified:   PortMaster/device_info.txt
	new file:   PortMaster/gptokeyb2.x86_64
	modified:   PortMaster/pylibs/harbourmaster/config.py
	modified:   PortMaster/pylibs/harbourmaster/platform.py
	new file:   PortMaster/retrodeck/PortMaster.txt
	new file:   PortMaster/retrodeck/control.txt

I now have Portmaster running via RetroDeck, PortMaster.sh and pugwash without errors.

I need to have another look and experiment with the do_realease for x86_64.

So will test that next.

I can imagine that retrodeck/PortMaster.txt and retrodeck/control.txt Might need some more stuff removing or adding.

I think this is functional enough to test ports running so will look at that know too.

2024-03-21 13:09 UTC, monkeyx-net commented
PPS I am manually copying retrodeck PortMaster.sh and control.txt files for now too.

2024-03-22 14:00 UTC, kloptops requested changes
You need to copy the `install_portmaster` from the `PlatformmuOS` and add it to the `PlatformRetroDECK`, then modify it there. Otherwise it looks good. 👍

2024-03-22 16:23 UTC, monkeyx-net commented on PortMaster/pylibs/harbourmaster/platform.py
> +        RD_DIR = self.hm.tools_dir / "PortMaster" / "retrodeck"
> Why is this code in the PlatformmuOS, not in the PlatformRetroDECK? :)

Just looking a this now. That's why we need curly braces in all languages.

I missed a tab or a space :)

2024-03-23 23:55 UTC, kloptops commented on PortMaster/pugwash
> +PORTMASTER_VERSION = '2024.03.21-1440'
This needs reverting.

2024-03-23 23:56 UTC, kloptops commented on PortMaster/pylibs/harbourmaster/platform.py
> +    def gamelist_add(self, gameinfo_file):
this code is specifically for muOS so it can be omitted. :)

2024-03-23 23:58 UTC, kloptops requested changes
Only two changes this time! :)

2024-03-25 14:16 UTC, merged